### PR TITLE
No longer experimental

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Is it no longer experimental? I.e. from 0.2. I at least could install, so the text was at least partially outdated.

**Comment by davnn** [comment]
Hi @PallHaraldsson,

that's true but the documentation is still lacking behind and it will take some more days for the (sub-) packages to be registered. Docs will probably be updated next week.

Best David

**Comment by davnn** [comment]
@all-contributors add @PallHaraldsson for docs

**Comment by davnn** [comment]
@all-contributors add @PallHaraldsson for docs

**Pull request merged**
